[build]
  command = "yarn run ci:build:design-system"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../components/ ../lighter-hooks ../lighter-styleguide"

[build.environment]
  NODE_VERSION = "lts/*"
  YARN_VERSION = "3.2.0"
  YARN_CACHE_FOLDER = "/opt/buildhome/.yarn_cache"