backend:
  name: github
  repo: adammockor/nextjs-mdx-netlify
local_backend: true
media_folder: public/img #images that are uploaded via Netlify Cms interface will be stored in this folder
public_folder: img #I dont know
collections:
  - name: 'components' # Used in routes, e.g., /admin/collections/blog
    label: 'Components' # Used in the UI
    label_singular: 'Component'
    folder: 'components' # The path to the folder where the markdown files are stored
    path: '{{title}}/{{slug}}'
    create: true # Allow users to create new markdown files.
    slug: '{{title}}.docs' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for front matter. You will need to modify fields according to your project.
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Docs', name: 'body', widget: 'markdown' }
    extension: 'mdx'
    format: 'frontmatter'
