import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Table examples</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Table examples</h1>
        <ul>
          <li>
            <Link href="/static">
              <a>Static data</a>
            </Link>
          </li>
          <li>
            <Link href="/fetched">
              <a>Fetched data</a>
            </Link>
          </li>
        </ul>
      </main>
    </div>
  );
};

export default Home;
