import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Forms examples</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Forms examples</h1>

        <ul>
          <li>
            <Link href="/simple">
              <a>Simple form</a>
            </Link>
          </li>
          <li>
            <Link href="/recaptcha">
              <a>Recaptcha form</a>
            </Link>
          </li>
          <li>
            <Link href="/complex">
              <a>Complex form</a>
            </Link>
          </li>
        </ul>
      </main>
    </div>
  );
};

export default Home;
